
Turn 2
================================================================
error: communication error with bot: read failed, errno was: 0 (Success)
Last input received was:


Bot error output was:
Traceback (most recent call last):
  File "MyBot.py", line 56, in <module>
    command_queue.append(intendMove(ship, random.choice([ Direction.North, Direction.South, Direction.East, Direction.West ])))
  File "MyBot.py", line 21, in intendMove
    logging.error(ship.position.directional_offset(direction).is_occupied)
AttributeError: 'Position' object has no attribute 'is_occupied'

